language: android
android:
  components:
    - build-tools-21.1.1
    - extra-android-m2repository

env:
  global:
    secure: l9oaircRM9VBHMbtM3R6D/xmwnTz2692hJlqEn8Rpf2wcPm7oAuvCGkSfh+9mkmwKcUOsm7QO8o/BOPWsIpZbxnjiXuiw6+n+XGQHG5wOEV5kBcofD1zsZao+FFG/GUE3nYtiMlwNzBGG78WmCzJ+svwZJn8AlAXrhDOsVJT79o=

before_install:
  - sudo pip install google-api-python-client
  - openssl aes-256-cbc -d -k "$file_password" -in app/gradle.properties.enc -out app/gradle.properties
  - cd ci
  - openssl aes-256-cbc -d -k "$file_password" -in vielengames.keystore.enc -out vielengames.keystore
  - openssl aes-256-cbc -d -k "$file_password" -in client_secrets.json.enc -out client_secrets.json
  - openssl aes-256-cbc -d -k "$file_password" -in androidpublisher.dat.enc -out androidpublisher.dat
  - python basic_list_apks.py com.vielengames
  - cd ..
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ci/wait_for_emulator

after_success:
  - cd ci
  - test $TRAVIS_BRANCH == "master" && ./deploy_google_play

notifications:
  email:
    - maciek.gorski@gmail.com

