language: android
android:
  components:
    - build-tools-19.1.0


before_install:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &


before_script:
  - ./ci/wait_for_emulator

script:
    - ./gradlew connectedAndroidTestProductionDebug

notifications:
  email:
    - maciek.gorski@gmail.com
    - siemionides@gmail.com
    - mb921028@gmail.com
    - pawelkobojek@gmail.com

